[package]
name = "ad_event_log_parser"
version = "0.1.0"
edition = "2021"
description = "A Rust parser for analyzing ad event logs to extract insights from click report data."
license = "MIT"
authors = ["Olha Horban olha.horban@ukma.edu.ua"]

[dependencies]
nom = "7.0"

